version: "1.0"

users:
  - user_config: config/users/example.yaml
    enabled: true

  - user_config: config/users/employee-002.yaml
    enabled: true

  - user_config: config/users/employee-003.yaml
    enabled: true
