name: Schedule Test

on:
  workflow_dispatch:

  # Test schedule: every day at 4:50 PM IST
  schedule:
    - cron: '50 16 * * *'
      timezone: "Asia/Kolkata"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm scheduler
        run: |
          echo "Scheduled workflow triggered successfully"
          date