name: Schedule Test

on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: "Asia/Kolkata"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm scheduler
        run: |
          echo "Scheduled workflow triggered successfully"
          date